apiVersion: v1
kind: Namespace
metadata:
  name: incident-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: incident-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: app
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo "service started"
              sleep 25
              exit 1
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
