apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: incident-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: app
          image: incident-catalog-service:v2
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
